server:
  port: 8083

spring:
  application:
    name: RESTTEMPLATE

eureka:
  client:
    service-url:
      defaultZone: http://mysql-container:8080/eureka

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      
      
#resilience4j.retry:
#  instances:
#    PRODUCT-SERVICE:
#      max-attempts: 3
#      wait-duration: 2s
#      retry-exceptions:
#        - org.springframework.web.client.HttpServerErrorException
#        - java.net.ConnectException
#      ignore-exceptions:
#        - org.springframework.web.client.HttpClientErrorException$NotFound

      
      
resilience4j:
  circuitbreaker:
    instances:
      PRODUCT-SERVICE:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

